name: Run JMeter Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  jmeter-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'

      - name: Download JMeter
        run: |
          JMETER_VERSION=5.6.3
          wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-$JMETER_VERSION.tgz
          tar -xzf apache-jmeter-$JMETER_VERSION.tgz
          mv apache-jmeter-$JMETER_VERSION jmeter-bin
          
      - name: Install Prometheus Listener Plugin
        run: |
          mkdir -p jmeter-bin/lib/ext
          wget https://github.com/johrstrom/jmeter-prometheus-plugin/releases/download/v0.5.0/jmeter-prometheus-plugin-0.5.0.jar \
            -O jmeter-bin/lib/ext/jmeter-prometheus-plugin.jar


      - name: Run JMeter test (non-GUI)
        run: |
          mkdir -p results
          ./jmeter-bin/bin/jmeter \
            -n \
            -t jmeter/tests/S01_JPetStore.jmx \
            -l results/results.jtl \
            -j results/jmeter.log \
            -Jenv=SIT

      - name: Upload JMeter results
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-results
          path: results/