name: Run JMeter Tests

on:
  push:
    branches: [ "main" ]
    paths:
      - "jmeter/tests/**/*.jmx"
      - "jmeter/tests/**/*.csv"
  pull_request:
    branches: [ "main" ]
    paths:
      - "jmeter/tests/**/*.jmx"
      - "jmeter/tests/**/*.csv"

jobs:
  jmeter-test:
    runs-on: ubuntu-latest

    env:
      RESULTS_DIR: "results_${{ github.run_id }}"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'

      - name: Download JMeter
        run: |
          JMETER_VERSION=5.6.3
          wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-$JMETER_VERSION.tgz
          tar -xzf apache-jmeter-$JMETER_VERSION.tgz
          mv apache-jmeter-$JMETER_VERSION jmeter-bin

      - name: Install JMeter Plugins Manager
        run: |
          wget https://repo1.maven.org/maven2/kg/apc/jmeter-plugins-manager/1.10/jmeter-plugins-manager-1.10.jar \
            -O jmeter-bin/lib/ext/jmeter-plugins-manager.jar
          wget https://repo1.maven.org/maven2/kg/apc/cmdrunner/2.3/cmdrunner-2.3.jar \
            -O jmeter-bin/lib/cmdrunner-2.3.jar
          java -cp jmeter-bin/lib/ext/jmeter-plugins-manager.jar org.jmeterplugins.repository.PluginManagerCMDInstaller

      - name: Copy Prometheus plugin
        run: |
          cp jmeter/lib/ext/jmeter-prometheus-plugin-0.6.0.jar jmeter-bin/lib/ext/

      - name: Prepare results folder
        run: mkdir -p $RESULTS_DIR

      - name: Run JMeter test (non-GUI)
        run: |
          ./jmeter-bin/bin/jmeter \
            -n \
            -t jmeter/tests/S01_JPetStore.jmx \
            -l $RESULTS_DIR/results.jtl \
            -j $RESULTS_DIR/jmeter.log \
            -Jenv=SIT \
            -Jsummariser.name=${{ github.run_id }}

      - name: Generate HTML Report
        run: |
          ./jmeter-bin/bin/jmeter \
            -g $RESULTS_DIR/results.jtl \
            -o $RESULTS_DIR/html

      - name: Upload Results
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-results-${{ github.run_id }}
          path: ${{ env.RESULTS_DIR }}

  publish-report:
    needs: jmeter-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download HTML report artifact
        uses: actions/download-artifact@v4
        with:
          name: jmeter-results-${{ github.run_id }}
          path: report

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: report

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4